name: Build and Test Git-Semver Tool

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup git-semver
        uses: ./.github/actions/setup-git-semver
        with:
          version: 'latest'

      - name: Test git-semver
        run: |
          git-semver